const frasesMotivadoras = [
  "Cree en ti y todo será posible.",
  "Cada día es una nueva oportunidad para mejorar.",
  "El éxito es la suma de pequeños esfuerzos repetidos cada día.",
  "Nunca es tarde para empezar de nuevo.",
  "Hazlo con pasión o no lo hagas.",
  "No sueñes tu vida, vive tu sueño.",
  "La disciplina tarde o temprano vencerá al talento.",
  "Lo único imposible es aquello que no intentas.",
  "Hoy es un buen día para intentarlo.",
  "Avanza un paso a la vez, pero no te detengas.",
  "No importa cuántas veces caigas, sino cuántas te levantas.",
  "Sé fuerte, el comienzo siempre es lo más difícil.",
  "Todo esfuerzo tiene su recompensa.",
  "El fracaso es solo una oportunidad para empezar de nuevo con más experiencia.",
  "La acción es la clave fundamental del éxito.",
  "No tengas miedo de ir lento, solo teme quedarte quieto.",
  "La perseverancia conquista lo imposible.",
  "Los límites solo están en tu mente.",
  "Hazlo con miedo, pero hazlo.",
  "Tu actitud determina tu altitud.",
  "Sueña en grande y atrévete a fallar.",
  "Cada día es una página en blanco, escríbela bien.",
  "Eres más fuerte de lo que crees.",
  "Confía en tu proceso.",
  "Haz hoy lo que otros no quieren, y mañana vivirás como otros no pueden.",
  "Nadie dijo que sería fácil, pero sí que valdría la pena.",
  "No pares hasta estar orgulloso.",
  "Hazlo por ti, por quien serás en el futuro.",
  "La motivación te inicia, el hábito te mantiene.",
  "Deja de esperar el momento perfecto y haz que el momento sea perfecto.",
  "Los grandes logros requieren tiempo y esfuerzo.",
  "El éxito es un viaje, no un destino.",
  "Cambia tus pensamientos y cambiarás tu mundo.",
  "Tu único límite eres tú.",
  "La diferencia entre ganar y perder es no rendirse.",
  "Si no trabajas por tus sueños, alguien te contratará para que trabajes por los suyos.",
  "Cree que puedes y ya estás a medio camino.",
  "Rodéate de personas que te inspiren a ser mejor.",
  "Haz de tu vida un sueño y de tu sueño una realidad.",
  "La vida comienza donde termina tu zona de confort.",
  "La clave del éxito es comenzar antes de estar listo.",
  "Nada cambia si tú no cambias.",
  "Sé el cambio que quieres ver en el mundo.",
  "No te detengas hasta que te sientas orgulloso.",
  "Haz lo mejor que puedas con lo que tengas.",
  "La constancia rompe cualquier resistencia.",
  "Levántate, suspira, sonríe y sigue adelante.",
  "Los sueños no funcionan a menos que tú trabajes por ellos.",
  "La vida es 10% lo que te pasa y 90% cómo reaccionas.",
  "El dolor es temporal, pero el orgullo es para siempre.",
  "Todo lo que necesitas ya está dentro de ti.",
  "El único fracaso es no intentarlo.",
  "No busques excusas, busca resultados.",
  "Tu futuro depende de lo que hagas hoy.",
  "Trabaja duro en silencio y deja que tu éxito haga el ruido.",
  "La mente es como un paracaídas: funciona mejor cuando está abierta.",
  "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
  "A veces perder es ganar experiencia.",
  "Haz que cada día cuente.",
  "Cuida tus pensamientos, se convierten en acciones.",
  "Lo mejor está por venir.",
  "Convierte los obstáculos en oportunidades.",
  "Si te caes siete veces, levántate ocho.",
  "Aprende a descansar, no a renunciar.",
  "El éxito no es para los que piensan en rendirse.",
  "El esfuerzo de hoy es el éxito de mañana.",
  "El éxito se construye cuando nadie te ve.",
  "Donde hay voluntad, hay un camino.",
  "Trabaja duro, sueña en grande, mantente humilde.",
  "Sin sacrificio no hay recompensa.",
  "Lo difícil se logra, lo imposible se intenta.",
  "Cada pequeño paso te acerca a tu meta.",
  "El que quiere, encuentra una forma.",
  "El que no quiere, encuentra una excusa.",
  "Haz que tu vida valga la pena.",
  "El tiempo es ahora.",
  "No esperes a que todo sea perfecto para empezar.",
  "No te compares, compite contigo mismo.",
  "El dolor te hace más fuerte, el miedo más valiente.",
  "Cree más en ti y menos en tus dudas.",
  "Los retos hacen la vida interesante.",
  "La actitud positiva atrae resultados positivos.",
  "Nunca dejes de aprender.",
  "El esfuerzo vence al talento cuando el talento no se esfuerza.",
  "El éxito es la suma de pequeños logros.",
  "Mantente firme aunque el camino sea difícil.",
  "Nunca subestimes el poder de un nuevo comienzo.",
  "Ve por lo que quieres, no por lo que crees que puedes.",
  "Hoy es el primer día del resto de tu vida.",
  "Haz que las cosas pasen.",
  "Actitud es una pequeña cosa que hace una gran diferencia.",
  "Trabaja como si alguien te estuviera observando.",
  "Sé la mejor versión de ti mismo.",
  "No hay progreso sin esfuerzo.",
  "Rompe tus propios límites.",
  "Tu historia apenas comienza.",
  "Construye la vida que sueñas.",
  "La acción vence al miedo.",
  "No te rindas antes de tiempo.",
  "Haz de tu vida una obra maestra.",
  "Lo más difícil es decidirse a actuar.",
  "Lo que haces hoy construye tu mañana.",
  "Nada que valga la pena es fácil.",
  "Tú puedes más de lo que imaginas.",
  "Persiste hasta lograrlo.",
  "Hazlo por los que creen en ti.",
]

export const getRandomQuote = ():string => {
  const index = Math.floor(Math.random() * frasesMotivadoras.length)
  return frasesMotivadoras[index]
}
